# ---------------------- #
# site config            #
# ---------------------- #
name: Perry Yeh
baseurl:
url: http://www.yeh.sh
keywords: Perry Yeh
description: A software engineer in Shanghai, China.

# ---------------------- #
# jekyll                 #
# ---------------------- #
safe: true
auto: true
rouge: true
markdown: kramdown
timezone: Asia/Shanghai

# ---------------------- #
# deployment             #
# ---------------------- #
deploy:
repository:
branch:

# ---------------------- #
# google analytics       #
# ---------------------- #
google_analytics: UA-11027907-1
